### ISSUE TITLE
#9 [견적서] : 기본 UI 세팅

### ISSUE THREAD

**Issue by kimgorok** [Web5rder/Web5rder-FE#5]
## 1. 무엇을?

상품 주문페이지 기본 UI를 세팅했습니다.

<br>

## 2. 상세 설명

상세한 디자인이 나오지 않아 간단하게 뼈대만 작업했습니다.

<br>

## 3. 추가 사항

디자인과 함께 다양한 기능을 추가하겠습니다.

**Comment by Minkyu0424** [comment]
아마 작업하신 내용이 상품 주문 페이지로 분류될 거 같아요 이슈 pr명 변경하면 좋을 거 같아요 제가 메인 화면 작업할게요!

**Comment by kimgorok** [comment]
수정했워요

**Comment by Minkyu0424** [comment]
얘 아직도 왜 살아있음?
